version: '3'

services:

  backend:
    container_name: pinokkio-backend
    build:
      context: ./backend/pinokkio
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/pinokkio?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=ssafy
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_REDIS_HOST=localhost
      - SPRING_REDIS_PORT=6379
      - SPRING_MAIL_USERNAME=${EMAIL}
      - SPRING_MAIL_PASSWORD=${EMAIL_PW}
      - JWT_SECRET=${JWT_SECRET}
      - BUCKET=${BUCKET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - REGION=${REGION}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mysql
      - redis

  fast_pinokkio:
    container_name: fast-pinokkio-backend
    build:
      context: ./backend/fast_pinokkio
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: pinokkio
    network_mode: host
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    network_mode: host

volumes:
  mysql-data:
