server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinokkio?serverTimezone=Asia/Seoul
    username: root
    password: ssafy!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.naver.com
    port: 465
    username: ${EMAIL}
    password: ${EMAIL_PW}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true
  jwt:
    secret: ${JWT_SECRET}


cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    region:
      static: ${REGION}
      auto: false
    stack:
      auto: false

s3:
  host:
    name: https://${BUCKET}.s3.${REGION}.amazonaws.com/

livekit:
  api:
    key: ${LIVEKIT_API_KEY}
    secret: ${LIVEKIT_API_SECRET}
